if(EXISTS "/mnt/g/Umer/Projects/Data_Structure/test/unit_tests[1]_tests.cmake")
  include("/mnt/g/Umer/Projects/Data_Structure/test/unit_tests[1]_tests.cmake")
else()
  add_test(unit_tests_NOT_BUILT unit_tests_NOT_BUILT)
endif()
